# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:15
from __future__ import unicode_literals

from django.db import migrations

from app.models import Rater


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160225_2253'),
    ]

    operations = [

    ]
