# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:20
from __future__ import unicode_literals

from django.db import migrations

from app.models import Review, Rater, Movie


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_auto_20160225_2315'),
    ]

    operations = [

    ]
