# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:25
from __future__ import unicode_literals

from django.db import migrations

from app.models import Review, Rater, Movie


def load_review_data(*args):
   with open("/Users/emilywivell/PycharmProjects/MovieReviews/app/static/ml-100k/u.data") as reviews:
       for review in reviews.readlines():
           tab = review.split('\t')
           Review.objects.create(reviewer=Rater(tab[0]), movie=Movie(tab[1]), rating=tab[2])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160225_2320'),
    ]

    operations = [
        migrations.RunPython(load_review_data)
    ]
