# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160225_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
    ]
