# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:26
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Avg


def add_averages(apps, schema_editor):
   Movie = apps.get_model('app', 'Movie')
   Review = apps.get_model('app', 'Review')
   for item in Movie.objects.all():
       averages = Review.objects.filter(movie=item).aggregate(Avg('rating'))
       item.avg_rating = averages['rating__avg']
       item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_movie_avg_rating'),
    ]

    operations = [
        migrations.RunPython(add_averages)
    ]
