# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [

    ]
