# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ureview_user_movie'),
    ]

    operations = [

    ]
